### ISSUE TITLE
Define Splitter interface

### ISSUE THREAD

**Issue by thiagovas** [LBD-UFMG/MachineLearning#4]
The splitter will be responsible for telling the tree which feature will be used to split the node and what is the value used as a threshold.

Proposal of properties:
- feature_weights --> The weight of each feature used in the information gain calculated at Criterion.
- documents_weights --> The weight used to calculate the probabilities used in the entropy formula calculate at Criterion.

**Comment by raphaelcampos** [comment]
I do it.

**Comment by raphaelcampos** [comment]
Closed by pull request #9 .
