### ISSUE TITLE
Define Point interface

### ISSUE THREAD

**Issue by thiagovas** [LBD-UFMG/MachineLearning#7]
_From @gcmgomes on July 13, 2016 10:53_

This should be the smallest building block we will have to use for any machine learning algorithm.
Any representations we wish to have must implement this interface.

_Copied from original issue: LBD-UFMG/Base#1_

**Comment by thiagovas** [comment]
_From @gcmgomes on July 13, 2016 10:55_

Will work on this.

**Comment by gcmgomes** [comment]
Closed by pull request #11.
